# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feddddab082a577cc0232323fb72bf05d5aabfd4f3c0867a2a121de3e46a30494d0d02ce94803e7f119b4ed9b1fb1f6fe3ea08d2339a552a5ef0f77a595967d1

test:
  secret_key_base: 176cdcfdf8dcd439511b9a2a1f49c2ef536401aa2bc5b4ac83280c35384ad47f11321cfeb9b1839893b154ef39823f2be90395fc7ab85d15ac2f23766d09834e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
